/**
 * SimpleRPG asset pipeline (TECHNICAL_ARCHITECTURE.md §10, ASSETS.md §5).
 *
 * game_assets/ (pristine sources)  →  public/assets/ (shipped, generated, git-ignored)
 *
 *   1. Kenney Fantasy UI Border PNGs → tinted 9-slice frames + /assets/nine-slice.css
 *   2. Low-poly backgrounds          → responsive WebP/AVIF + LQIP placeholders
 *   3. game-icons/original SVGs      → single symbol sprite + typed id registry (src/ui/icons.gen.ts)
 *
 * Incremental: a manifest hash of all inputs + this script skips work when nothing changed.
 * game_assets/examples/ is reference-only and is never read or shipped (ASSETS.md §3).
 */
import { createHash } from 'node:crypto';
import { mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC_BORDERS = path.join(ROOT, 'game_assets/UI/Kenney_FantasyUIBorders/PNG');
const SRC_BG = path.join(ROOT, 'game_assets/UI/Backgrounds');
const SRC_ICONS = path.join(ROOT, 'src/assets/icons');
const OUT = path.join(ROOT, 'public/assets');
const MANIFEST = path.join(OUT, 'manifest.json');

// ---------------------------------------------------------------------------
// Configuration — mirrors UI_DESIGN.md §2 (tints) and §3 (frame table).
// ---------------------------------------------------------------------------
const TINTS = {
  gold: '#D9A94B',
  goldbright: '#F0C75E',
  silver: '#8FA3BC',
  arcane: '#3FA7A0',
  danger: '#C0483F',
  muted: '#5E6A7A',
  common: '#9AA3AD',
  uncommon: '#57B65F',
  rare: '#4C8BE0',
  epic: '#A64CE0',
  legendary: '#E08A2E',
  set: '#35C99A',
  warrior: '#D96A45',
  scout: '#6FA85A',
  mage: '#5B8DD9',
  assassin: '#9B6DD9',
};

/** frame token → { file, tints, borderWidthPx (CSS default at 1x) } */
const FRAMES = {
  primary: { file: 'Default/Border/panel-border-007.png', tints: ['gold', 'muted'], width: 16 },
  secondary: {
    file: 'Default/Border/panel-border-013.png',
    tints: ['silver', 'muted', 'gold'],
    width: 12,
  },
  slot: {
    file: 'Default/Border/panel-border-001.png',
    tints: [
      'muted',
      'gold',
      'common',
      'uncommon',
      'rare',
      'epic',
      'legendary',
      'set',
      'warrior',
      'scout',
      'mage',
      'assassin',
    ],
    width: 10,
  },
  button: {
    file: 'Default/Border/panel-border-004.png',
    tints: ['gold', 'muted', 'danger', 'arcane'],
    width: 10,
  },
  special: { file: 'Default/Border/panel-border-029.png', tints: ['arcane', 'gold'], width: 16 },
  danger: { file: 'Default/Border/panel-border-027.png', tints: ['danger'], width: 14 },
  legendary: { file: 'Double/Border/panel-border-007.png', tints: ['goldbright'], width: 16 },
};

const FRAME_SCALE = 2; // 48px art rendered at 96px for crisp hi-dpi border-image
const BG_WIDTHS = [1920, 1280, 640];

// ---------------------------------------------------------------------------
// Incremental manifest
// ---------------------------------------------------------------------------
async function listFiles(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await listFiles(p)));
    else out.push(p);
  }
  return out.sort();
}

async function inputsHash() {
  const hash = createHash('sha256');
  const self = await readFile(fileURLToPath(import.meta.url));
  hash.update(self);
  const inputs = [
    ...Object.values(FRAMES).map((f) => path.join(SRC_BORDERS, f.file)),
    ...(await listFiles(SRC_BG)),
    ...(await listFiles(SRC_ICONS)),
  ];
  for (const file of inputs) {
    const s = await stat(file);
    hash.update(`${file}:${s.size}:${s.mtimeMs};`);
  }
  return hash.digest('hex');
}

// ---------------------------------------------------------------------------
// 1. Frames
// ---------------------------------------------------------------------------
async function buildFrames() {
  const dir = path.join(OUT, 'frames');
  await mkdir(dir, { recursive: true });
  const cssBlocks = [
    '/* GENERATED by scripts/optimize-assets.mjs — do not edit (UI_DESIGN.md §3). */',
    `:root { --frame-w: 16px; }`,
    `[class*='frame-'] { border-style: solid; border-color: transparent; }`,
  ];
  const size = 48 * FRAME_SCALE;
  const slice = 16 * FRAME_SCALE;

  for (const [token, def] of Object.entries(FRAMES)) {
    const srcPath = path.join(SRC_BORDERS, def.file);
    const base = await sharp(srcPath)
      .ensureAlpha()
      .resize(size, size, { kernel: 'nearest' })
      .png()
      .toBuffer();

    for (const tintName of def.tints) {
      const color = TINTS[tintName];
      const out = path.join(dir, `${token}-${tintName}.png`);
      await sharp({ create: { width: size, height: size, channels: 4, background: color } })
        .composite([{ input: base, blend: 'dest-in' }])
        .png({ compressionLevel: 9 })
        .toFile(out);

      const cls = tintName === def.tints[0] ? `.frame-${token}` : `.frame-${token}--${tintName}`;
      cssBlocks.push(
        `${cls} { border-width: var(--frame-w, ${def.width}px); ` +
          `border-image: url('/assets/frames/${token}-${tintName}.png') ${slice} / var(--frame-w, ${def.width}px) stretch; }`,
      );
    }
  }
  await writeFile(path.join(OUT, 'nine-slice.css'), cssBlocks.join('\n') + '\n');
  return Object.entries(FRAMES).reduce((n, [, d]) => n + d.tints.length, 0);
}

// ---------------------------------------------------------------------------
// 2. Backgrounds
// ---------------------------------------------------------------------------
async function buildBackgrounds() {
  const dir = path.join(OUT, 'bg');
  await mkdir(dir, { recursive: true });
  const files = (await readdir(SRC_BG)).filter((f) => f.endsWith('.png'));
  const lqip = {};

  await Promise.all(
    files.map(async (file) => {
      const name = file.replace(/\.png$/, '');
      const src = sharp(path.join(SRC_BG, file));
      for (const width of BG_WIDTHS) {
        await src
          .clone()
          .resize({ width, withoutEnlargement: true })
          .webp({ quality: 78 })
          .toFile(path.join(dir, `${name}-${width}.webp`));
      }
      // AVIF only at the two widths screens actually use full-bleed (build-time cost control).
      for (const width of [1920, 1280]) {
        await src
          .clone()
          .resize({ width, withoutEnlargement: true })
          .avif({ quality: 50, effort: 3 })
          .toFile(path.join(dir, `${name}-${width}.avif`));
      }
      const tiny = await src.clone().resize({ width: 24 }).webp({ quality: 40 }).toBuffer();
      lqip[name] = `data:image/webp;base64,${tiny.toString('base64')}`;
    }),
  );
  return { count: files.length, lqip };
}

// ---------------------------------------------------------------------------
// 3. Icon sprite + typed registry
// ---------------------------------------------------------------------------
const BG_RECT_D = /^M0 0h512v512H0z$/i;

async function buildIcons() {
  const files = (await readdir(SRC_ICONS)).filter((f) => f.endsWith('.svg')).sort();
  const symbols = [];
  const ids = [];

  for (const file of files) {
    const name = file.replace(/\.svg$/, '');
    const svg = await readFile(path.join(SRC_ICONS, file), 'utf8');
    const paths = [...svg.matchAll(/<path\b[^>]*\bd="([^"]+)"[^>]*\/?>(?:<\/path>)?/g)]
      .map((m) => m[1])
      .filter((d) => !BG_RECT_D.test(d.trim()));
    if (paths.length === 0) throw new Error(`icon ${file}: no foreground paths found`);
    const body = paths.map((d) => `<path fill="currentColor" d="${d}"/>`).join('');
    symbols.push(`<symbol id="i-${name}" viewBox="0 0 512 512">${body}</symbol>`);
    ids.push(name);
  }

  const sprite = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">${symbols.join('')}</svg>`;
  await writeFile(path.join(OUT, 'icons.svg'), sprite);

  const gen = [
    '// GENERATED by scripts/optimize-assets.mjs from src/assets/icons/ — do not edit.',
    'export const ICON_IDS = [',
    ...ids.map((id) => `  '${id}',`),
    '] as const;',
    '',
    'export type IconId = (typeof ICON_IDS)[number];',
    '',
  ].join('\n');
  await writeFile(path.join(ROOT, 'src/ui/icons.gen.ts'), gen);
  return ids.length;
}

// ---------------------------------------------------------------------------
/**
 * The iOS home-screen tile.
 *
 * iOS Safari ignores the web manifest's `icons` array entirely and refuses SVG
 * for `apple-touch-icon`, so without this the one platform whose standalone
 * meta tags we set would pin a blank or screenshot-derived square. 180px is the
 * largest size iOS asks for; it downsamples the rest itself. Opaque background,
 * because iOS composites the tile onto white and a transparent mark disappears.
 */
async function buildAppleTouchIcon() {
  const svg = await readFile(path.join(ROOT, 'public/favicon.svg'));
  const size = 180;
  const mark = await sharp(svg, { density: 384 })
    .resize(Math.round(size * 0.72), Math.round(size * 0.72), {
      fit: 'contain',
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    })
    .png()
    .toBuffer();
  await sharp({
    create: { width: size, height: size, channels: 4, background: '#0e1420' },
  })
    .composite([{ input: mark, gravity: 'center' }])
    .png({ compressionLevel: 9 })
    .toFile(path.join(OUT, 'apple-touch-icon.png'));
}

async function main() {
  const started = performance.now();
  const hash = await inputsHash();
  try {
    const prev = JSON.parse(await readFile(MANIFEST, 'utf8'));
    if (prev.hash === hash) {
      console.log('[assets] up to date, skipping.');
      return;
    }
  } catch {
    /* first run or manifest unreadable → rebuild */
  }

  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });

  await mkdir(path.join(ROOT, 'src/ui'), { recursive: true });
  const [frameCount, bg, iconCount] = await Promise.all([
    buildFrames(),
    buildBackgrounds(),
    buildIcons(),
    buildAppleTouchIcon(),
  ]);

  await writeFile(
    MANIFEST,
    JSON.stringify({ hash, generatedAt: new Date().toISOString(), lqip: bg.lqip }, null, 2),
  );
  const secs = ((performance.now() - started) / 1000).toFixed(1);
  console.log(
    `[assets] built ${frameCount} frames, ${bg.count} backgrounds, ${iconCount} icons in ${secs}s`,
  );
}

await main();
